In [2]:
#from dv import AedatFile
import numpy as np

In [3]:
aedat_file = "../dataset/KH/night/raw_aedat/2020_07_29_19_50_07.aedat4"
with AedatFile(aedat_file) as f:
    # events will be a named numpy array
    events = np.hstack([packet for packet in f['events'].numpy()])

    # Access information of all events by type
    timestamps, x, y, polarities = events['timestamp'], events['x'], events['y'], events['polarity']
print(timestamps)

[1596019806543106 1596019806543117 1596019806543126 ... 1596020311753074
 1596020311753074 1596020311753086]


In [ ]:
1596020302 

In [3]:
import numpy as np
location = "/home/student1/hyeongilee/slayerPytorch/example/dataset/KH/rain/raw_numpy_100ms/2020_07_30_17_51_53/"
np_file = np.load(location+"100.npy")

print(np_file[:200])

[[155  93   1   0]
 [149  30   1   0]
 [149   8   1   0]
 [145  72   1   0]
 [138  17   1   0]
 [137  21   1   0]
 [136  86   1   0]
 [136  39   1   0]
 [136  33   1   0]
 [135   3   1   0]
 [132  21   1   0]
 [131  80   1   0]
 [131  74   1   0]
 [129  35   1   0]
 [128   9   1   0]
 [128  88   1   0]
 [127   9   1   0]
 [127  26   1   0]
 [126   9   1   0]
 [124   9   1   0]
 [122  92   1   0]
 [121  20   1   0]
 [121  28   1   0]
 [119  99   1   0]
 [118  93   1   0]
 [117  79   1   0]
 [117  95   1   0]
 [115  57   1   0]
 [115  49   1   0]
 [113  84   1   0]
 [113  40   1   0]
 [112  49   1   0]
 [111  10   1   0]
 [111  24   1   0]
 [109  20   1   0]
 [107  10   1   0]
 [106  79   1   0]
 [105  42   1   0]
 [105  33   1   0]
 [105  40   1   0]
 [104  55   1   0]
 [104  32   1   0]
 [102  53   1   0]
 [101  53   1   0]
 [100  75   1   0]
 [ 98  18   1   0]
 [ 97  38   1   0]
 [ 95  70   1   0]
 [ 95  19   1   0]
 [ 92  19   1   0]
 [ 91  22   1   0]
 [ 90  19   1   0]
 [ 90  24   